Fix the black body SEDs of the Disk and the Dust Torus
cosimoNigro/agnpy pull request #92
Opened 2021-05-08 10:32 UTC by cosimoNigro

Dear @jsitarek,

this PR implements a correct multi-temperature black body SED for the Disk and a (single-temperature) black body SED for the DT.
I renormalise these SEDs to the respective luminosities of the Disk and DT, i.e. I impose that the integral luminosity of the SED has to be equal to the luminosity of the disk (or the luminosity of the DT).
I added these checks of the luminosity to the tests.

This should solve #23.

Changes in files other than `targets.py` and `test_targets.py` are unrelated, and need no checking, they are mostly corrections of the docstrings.

Here a snippet to test the changes, developed on the notebook you posted in issue #23 (`checkout fix_disk_and_dt_bb`)
```python
import numpy as np
import astropy.units as u
from astropy.constants import M_sun
from astropy.coordinates import Distance
import matplotlib.pyplot as plt
from agnpy.targets import SSDisk, RingDustTorus
from agnpy.utils.plot import load_mpl_rc, plot_sed

load_mpl_rc()

# create disks with same luminosity but different radii
L_disk = 6 * 1e44 * u.Unit("erg s-1")
M_BH = 1e8 * M_sun
z = 0.06
disk1 = SSDisk(M_BH, L_disk, 1 / 12, 6, 100, R_g_units=True)
disk2 = SSDisk(M_BH, L_disk, 1 / 12, 6, 1000, R_g_units=True)
disk3 = SSDisk(M_BH, L_disk, 1 / 12, 6, 10000, R_g_units=True)

nu = np.logspace(10, 20, 100) * u.Hz
sed_disk1 = disk1.sed_flux(nu, z)
sed_disk2 = disk2.sed_flux(nu, z)
sed_disk3 = disk3.sed_flux(nu, z)

plot_sed(nu, sed_disk1, ls="-", label=r"$R_{\rm out} = 10^2 R_{\rm g}$")
plot_sed(nu, sed_disk2, ls="-", label=r"$R_{\rm out} = 10^3 R_{\rm g}$")
plot_sed(nu, sed_disk3, ls="-", label=r"$R_{\rm out} = 10^4 R_{\rm g}$")
plt.ylim([1e-15, 1e-9])
plt.legend()
plt.show()

# compute back the luminosity
print(f"disk reference Luminosity: {L_disk:.2e}")
d_L = Distance(z=z).to("cm")
for sed in [sed_disk1, sed_disk2, sed_disk3]:
    F_nu = sed / nu
    L = 4 * np.pi * np.power(d_L, 2) * np.trapz(F_nu, nu, axis=0)
    print(f"SED luminosity: {L:.2e}")

# create dust toruses with same luminosity but different radii
xi_dt = 0.5
dt1 = RingDustTorus(L_disk, xi_dt, 1000 * u.K)
dt2 = RingDustTorus(L_disk, xi_dt, 2000 * u.K)
dt3 = RingDustTorus(L_disk, xi_dt, 5000 * u.K)

nu = np.logspace(10, 20, 100) * u.Hz
sed_dt1 = dt1.sed_flux(nu, z)
sed_dt2 = dt2.sed_flux(nu, z)
sed_dt3 = dt3.sed_flux(nu, z)
plot_sed(nu, sed_dt1, ls="-", label=r"$T_{\rm dt} = 10^3 \, {\rm K}$")
plot_sed(nu, sed_dt2, ls="-", label=r"$T_{\rm dt} = 2 \times 10^3 \, {\rm K}$")
plot_sed(nu, sed_dt3, ls="-", label=r"$T_{\rm dt} = 5 \times 10^3 \, {\rm K}$")
plt.ylim([1e-15, 1e-9])
plt.legend()
plt.show()

# compute back the luminosity
L_dt = xi_dt * L_disk
print(f"DT reference Luminosity: {L_dt:.2e}")
d_L = Distance(z=z).to("cm")
for sed in [sed_dt1, sed_dt2, sed_dt3]:
    F_nu = sed / nu
    L = 4 * np.pi * np.power(d_L, 2) * np.trapz(F_nu, nu, axis=0)
    print(f"SED luminosity: {L:.2e}")
```
![Figure_1](https://user-images.githubusercontent.com/26409711/117536094-72a3ff80-aff9-11eb-880e-73c58154c714.png)
```shell
disk reference Luminosity: 6.00e+44 erg / s
SED luminosity: 6.00e+44 erg / s
SED luminosity: 6.00e+44 erg / s
SED luminosity: 6.00e+44 erg / s
```
![Figure_2](https://user-images.githubusercontent.com/26409711/117536092-720b6900-aff9-11eb-85c2-62d27d9d228b.png)
```shell
DT reference Luminosity: 3.00e+44 erg / s
SED luminosity: 3.00e+44 erg / s
SED luminosity: 3.00e+44 erg / s
SED luminosity: 3.00e+44 erg / s
```

2021-05-12 14:01 UTC, jsitarek requested changes
sorry for a delay on checking this code, I spotted an issue with lack of observation angle dependence on the disk luminosity.

2021-06-25 10:59 UTC, cosimoNigro commented on agnpy/targets/targets.py
>          r"""temperature of the disk at radius :math:`\tilde{R}`.
corrected

2021-06-25 11:00 UTC, cosimoNigro commented on agnpy/targets/targets.py
> +        norm = (L_disk / L).to_value("")
done, I have included the cosine in the SED calculation (in order to obtain the correct nuFnu depending on the viewing angle) and added the factor 2 in the luminosity calculations

2021-06-25 11:00 UTC, cosimoNigro commented on agnpy/tests/test_targets.py
> +        assert u.isclose(L, L_disk_test, atol=0 * u.Unit("erg s-1"), rtol=1e-2)
done

2021-06-25 11:10 UTC, jsitarek commented on agnpy/tests/test_targets.py
> +        assert u.isclose(L, L_disk_test, atol=0 * u.Unit("erg s-1"), rtol=1e-2)
the test is done for observation angle=0, do you think it is work to include in the parametrizaiton also a second case with observation at an angle (to check those cos factors), or would it be overdoing the testing?

2021-06-25 11:18 UTC, cosimoNigro commented
Hello @jsitarek,

so sorry for the huge delay in this, June has been full of meetings!

I took into account in your suggestions, now I multiply the nuFnu SED by the cosine of the viewing angle (newly introduced `mu_s` parameter with default 1). This way we get the correct SED value for an inclined observer. 
This is how the docstring reads:
<img width="659" alt="Screenshot 2021-06-25 at 12 56 50" src="https://user-images.githubusercontent.com/26409711/123415734-fb7cf780-d5b5-11eb-8032-eb58fd5cf144.png">

I am not totally convinced it is sufficient to multiply by cosine to get the correct integral, maybe it works only when you simplify `R^2/d_L^2` to 1?
To be honest I am not sure how to go from the `mu`s in blue to the green ones in the figure I sketched
![photo1624619420](https://user-images.githubusercontent.com/26409711/123416867-62e77700-d5b7-11eb-8400-56cf7a16f959.jpeg)
When you incline the observer you change not only the viewing angles but also the distances to the disk surface...
Only reference I found giving this formula is [this one](https://www.aanda.org/articles/aa/pdf/2001/32/aa1141.pdf), Eq. 10.

Beside the mathematical discussion, are you satisfied with the changes now?
Thanks!
Cosimo

2021-06-25 11:34 UTC, jsitarek commented
thx @cosimoNigro 
I'm not sure what do you mean by "when you simplify R^2/d_L^2 to 1?"

the function is used to determine the SED of the whole disk at the observer, i.e. you integrate the full disk, and then I think cos should work fine (it is also there in the formula in the reference that you provided. As far as I can understand it , the cos is there due to the black body property, it simply emits more perpendicularly to the surface than at an angle to it. And since the solid angle in which you see the disk is very small, also the change of distances along it does not matter. 

The situation gets more complicated when you are close to the disk, and see the emission from its different points at different angles, than you also need to take into account that with a given small solid angle you will also catch a different part of the disk surface depending on this viewing angle. This needs to be taken into account when computing EC and absorption from disk, but for just showing the disk SED at the observer is not important

2021-06-25 11:41 UTC, cosimoNigro commented on agnpy/tests/test_targets.py
> +        assert u.isclose(L, L_disk_test, atol=0 * u.Unit("erg s-1"), rtol=1e-2)
Thanks for asking to add it, made me realise that the new variable `mu_s` was not propagated to all the functions computing the SEDs. Now it should be ok.

2021-06-25 11:47 UTC, cosimoNigro commented
> I'm not sure what do you mean by "when you simplify R^2/d_L^2 to 1?"

if you compare Eq. 10 of the paper and the formula in the docstrings I wrote it's clear they are simplifying the factor (`1 + R^2/d_L^2`) by assuming `R << d_L`, right? I thought that only in that case you could transform everything multiplying just by the cosine of the viewing angle. But I think I was wrong.

Let me know if you are satisfied with the changes (you can merge if you are).

Sorry again for taking so long.

2021-06-25 12:02 UTC, jsitarek commented
Hi @cosimoNigro 
Now I understand what you mean, the formula is only valid for distant observer, so R<< d_L. 

cos angle to the surface normal is always there, but only if the observer is far away from the disk it is the same angle as the observation angle. If you need to calculate it close to the disk, not only the distances will vary, but also each part of the disk will be observed at a different angle. I think this function is only meant for plotting SED for distant observer, then I suggest that the doc string is revised to take this into account, and give the cosine explicitely. If you need a similar function for computing the density of the photons from the disk either for IC or for pair production, this is more complicated, but since those functions were implemented from Dermen's and Finke's paper they should already have this cosine hidden somewhere.

2021-06-25 14:46 UTC, cosimoNigro commented
What about now?

![Screenshot from 2021-06-25 16-43-25](https://user-images.githubusercontent.com/26409711/123441791-866cea80-d5d4-11eb-8ac5-f6bc11d34547.png)

> this is more complicated, but since those functions were implemented from Dermen's and Finke's paper they should already have this cosine hidden somewhere.

looking at the formulas that we re-written and the schemes we drawn I think it is always assumed that the disk axis matches the jet axis, which I think it's fine for most calculations. It's the observer that is in turn inclined to an angle `\theta_s` to the jet (and disk axis).

2021-06-25 15:01 UTC, jsitarek commented
Sorry for being picky, but I think that the part 1+ R^2 /dL^2 is really confusing here. The formula is correct only if R<< dL, so I would suggest to skip this (1+...).
Otherwise it gives an impression that it might work also close to the disk (even if the docstring says overwise)

2021-06-25 15:27 UTC, cosimoNigro commented
No problem, removed that factor from the docs, and of course from the actual formula in the code!
![Screenshot from 2021-06-25 17-24-35](https://user-images.githubusercontent.com/26409711/123447825-912a7e00-d5da-11eb-9711-c7ab81d6536f.png)

2021-06-25 15:33 UTC, jsitarek commented
I think it is fine now, thx

2021-06-25 15:45 UTC, cosimoNigro commented
I think you have to accept my changes or accept the review, it still says changes requested.
After that you can merge yourself.

2021-06-25 15:54 UTC, jsitarek approved these changes

2021-06-25 15:55 UTC, merged

2021-06-25 15:56 UTC, jsitarek commented
right, sorry, I just accepted the review and merged